# prevent duplicate builds on PR pushes
branches:
  only:
  - master
  - /^v\d/

matrix:
  include:
    - os: linux
      dist: trusty
      language: cpp
      compiler: gcc

      before_install:
        - sudo apt-get install libgtkmm-2.4-dev
        - sudo apt-get install libboost-locale-dev

      script:
        - mkdir __build
        - cd __build
        - cmake ../build/clion
        - make

    - os: osx
      osx_image: xcode9.3
      language: objective-c

      env: >
            BUILDPATH="./DerivedData"
            PROJECTPATH="build/xcode/9.3 (mojave 10.14)/OpenWL.xcodeproj"

      script:
        - set -o pipefail && xcodebuild -project "$PROJECTPATH" -scheme "OpenWL-Release" -derivedDataPath "$BUILDPATH" -destination 'platform=macOS' clean build test | xcpretty

      before_deploy:
        - mkdir dmg_contents
        - cp -R "$BUILDPATH/Build/Products/Release/OpenWL.framework" dmg_contents/
        - export DMG_FNAME=OpenWL.dmg
        - hdiutil create $DMG_FNAME -srcfolder dmg_contents/ -ov
        - python ci/travis/gen_bintray.py $TRAVIS_TAG
        - cat bintray.json

      # deploy:
      #   provider: releases
      #   api_key:
      #     secure: fMejPDpc8TGyLPzJhFKwMkoevJCIZD54OzD1YfhPl1MTtepeJBexOX5VWv8ShGiBwXbSKEgTv9EusxL05wH+CwTAxeZS4txWktadhZmv/VsYFHRcHsJaVflcepaTYUzJULwErfKpaLiuz/LxB6BNPq3Rdu2Y4ITIGFs14lnTcjKNq6MG3TskqSCjISCHBNRZ3bYj57nCOois34aFCjcWRTpnGq6eM4EDwkagGQb3gpxgcLETck06y+Sc0F8gxXYtFHn77Rd0LlcgIdEqVhv/SAxhvbGtLG6xjHqStv+UcNiCLUr4u7JsymVTyHSwZO7OhaSe4YYLzTu5C7+vHQoXF4OWB1krnmN4pSwct++o6pm24FGxMbp3DbJdqV83X/hv09513zvD8e4INiSrdUf8hKOOf27NOkFC7Nue5xj65hIBdzCC3+L9Wz/Bt5z8p+H8Im7OWvUC0gDfWC+YccISXMlXo6pXnE8KnEPLZM5n97d0XDIymdLCAgU6rv27dMMbtJtr/QhibS4Aqn7VVOcIShD2D+6SC6fCpW2pWEsPBbTmhUIe6Kc3+iEsAVCph+Z5rM26UG6TguKk3MqvyuAPaKip7MfpeYUroh/gp7yHDF6qEGYKFZt4+h7HfNYHGdQGZe+HqXmoADF48OSCrSICixfAl0TYZOkWTji+SY62/sM=
      #   file: $DMG_FNAME
      #   skip_cleanup: true
      #   draft: true
      #   name: OpenWL-$TRAVIS_TAG
      #   on:
      #     repo: dewf/openwl
      #     tags: true

      deploy:
        provider: bintray
        file: bintray.json
        user: dewf
        key:
          secure: s+F+tmTeW98nNjD07b6Vx8wK4ZufCQax/zB80oHPDFrTnQcf5VIT3mx4bezNQ5rR8jTEbL/mpyISlqbkZYRL27Td/4NuoKuTgUrJ4jB9pXrhonXRDk0JqufjZ/4qisEJT7jgSnPODjIgrA0HFsWc18iF75znmqWSisIwmYUo+jpiHLAzjZES6/KYmo8K9/X5ypTj24pIyhek/Gl+OtdR9bZfObB9bpO7O2QF9yCJytz//wk7eH8tHn9XXw3sxMrxOg9ddiuPy/rTsW//sqTdkyMLXje/3vjMo8GMiRurhi2ao3RY7fHWBPDgwPT0K59Xx/HY5cOuH9CSRfL3kCgVE/GSUmdd6M1YTfDhqmmPJ3RdEjWJxdhUgCK4BveU4xwuQL855KhHpxCUp3duGRpaaIY9gOQWgwU2SUVlaS0QGj1eHnPfak5E94RO5pBaliHSB/vlKdRuQVUsznRQ5IQ1zetAGQmmNlllqhZJbQIr33TGBdMPt+XKRfeePDImVeUbPpXnLVCQUjdxZOS38pnmtWceT4bMR7gzBQEC8UYIL0ypIxNSXe2iFuwWRfuwT5XJXsU1BRTSGo6Dte9QUKTMygDLG6qOEAtyv09UHOVc4oo0WiR4dEeJyp7/jvCIM26dlhxVhs1c/jfZsIQ2xqjSg/9ZI2R4ZyNAmFpZHyTWrlE=
        on:
          repo: dewf/openwl
          tags: true
        skip_cleanup: true







