version: 0.1.{build}
skip_branch_with_pr: true  # don't launch jobs twice for working on my own branches
image: Visual Studio 2017
configuration:
  # - Debug
  - Release
platform:
  - x86
  - x64

for:
-
  matrix:
    only:
      - platform: x86
  
  environment:
    VCPKG_LIBS_FNAME: vcpkg-x86-boost-icu
    VCPKG_LIBS_URL: https://dl.dropbox.com/s/b90kkd0dru8hbif/vcpkg-x86-boost-icu.7z?dl=0
    ARTIFACT_NAME: OpenWL-Windows-x86-%CONFIGURATION%
    BINARY_ROOT: build\msvc\2017

-
  matrix:
    only:
      - platform: x64
  
  environment:
    VCPKG_LIBS_FNAME: vcpkg-x64-boost-icu
    VCPKG_LIBS_URL: https://dl.dropbox.com/s/5exezlmunyuo0re/vcpkg-x64-boost-icu.7z?dl=0
    ARTIFACT_NAME: OpenWL-Windows-x64-%CONFIGURATION%
    BINARY_ROOT: build\msvc\2017\x64

matrix:
  fast_finish: true
  
cache:
  - C:\ProgramData\chocolatey\bin
  - C:\ProgramData\chocolatey\lib
  - C:\Downloads
  # - C:\tools\vcpkg\installed\

install:
  - choco install 7zip
  - if not exist C:\Downloads ( mkdir C:\Downloads )
  - cd C:\Downloads
  - if not exist %VCPKG_LIBS_FNAME%.7z ( appveyor DownloadFile %VCPKG_LIBS_URL% )
  - 7z x %VCPKG_LIBS_FNAME%.7z -aos -oc:\tools\vcpkg
  - cd c:\tools\vcpkg
  - vcpkg integrate install

build:
  project: build/msvc/2017/openwl.sln
  parallel: true
  verbosity: normal

after_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - 7z a %ARTIFACT_NAME%.zip .\%BINARY_ROOT%\%CONFIGURATION%\openwl.lib .\%BINARY_ROOT%\%CONFIGURATION%\*.dll

artifacts:
  - path: '%ARTIFACT_NAME%.zip'
    name: '%ARTIFACT_NAME%'

# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
